/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtShrinkFilter.C
// ************************************************************************* //

#include <avtShrinkFilter.h>
#include <vtkShrinkFilter.h>
#include <vtkUnstructuredGrid.h>
#include <vtkDataSet.h>


// ****************************************************************************
//  Method: avtShrinkFilter constructor
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
// ****************************************************************************

avtShrinkFilter::avtShrinkFilter()
{
}


// ****************************************************************************
//  Method: avtShrinkFilter destructor
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
//  Modifications:
//
// ****************************************************************************

avtShrinkFilter::~avtShrinkFilter()
{
}


// ****************************************************************************
//  Method:  avtShrinkFilter::Create
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
// ****************************************************************************

avtFilter *
avtShrinkFilter::Create()
{
    return new avtShrinkFilter();
}


// ****************************************************************************
//  Method:      avtShrinkFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
// ****************************************************************************

void
avtShrinkFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const Scale*)a;
}


// ****************************************************************************
//  Method: avtShrinkFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtShrinkFilter with the given
//      parameters would result in an equivalent avtShrinkFilter.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
// ****************************************************************************

bool
avtShrinkFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(Scale*)a);
}


// ****************************************************************************
//  Method: avtShrinkFilter::ExecuteData
//
//  Purpose:
//      Sends the DataSet through the shrink filter.
//
//  Returns:       The output dataset.
//
//  Programmer: kamek -- generated by xml2avt
//  Creation:   Fri Nov 29 23:14:00 PST 2013
//
// ****************************************************************************

vtkDataSet *
avtShrinkFilter::ExecuteData(vtkDataSet *dataSet, int, std::string)
{
    vtkShrinkFilter *shrinker = vtkShrinkFilter::New();
    shrinker->SetInputData(dataSet);
    shrinker->SetShrinkFactor(atts.GetScaleFactor());
    shrinker->Update();
    
    dataSet = shrinker->GetOutput();

    return dataSet;
}
