/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PyScale.h>
#include <ObserverToCallback.h>
#include <stdio.h>
#include <snprintf.h>

// ****************************************************************************
// Module: PyScale
//
// Purpose: 
//   Set scale factor
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   omitted
//
// ****************************************************************************

//
// This struct contains the Python type information and a Scale.
//
struct ScaleObject
{
    PyObject_HEAD
    Scale *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewScale(int);

std::string
PyScale_ToString(const Scale *atts, const char *prefix)
{
    std::string str; 
    char tmpStr[1000]; 

    SNPRINTF(tmpStr, 1000, "%sScaleFactor = %g\n", prefix, atts->GetScaleFactor());
    str += tmpStr;
    return str;
}

static PyObject *
Scale_Notify(PyObject *self, PyObject *args)
{
    ScaleObject *obj = (ScaleObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
Scale_SetScaleFactor(PyObject *self, PyObject *args)
{
    ScaleObject *obj = (ScaleObject *)self;

    double dval;
    if(!PyArg_ParseTuple(args, "d", &dval))
        return NULL;

    // Set the ScaleFactor in the object.
    obj->data->SetScaleFactor(dval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
Scale_GetScaleFactor(PyObject *self, PyObject *args)
{
    ScaleObject *obj = (ScaleObject *)self;
    PyObject *retval = PyFloat_FromDouble(obj->data->GetScaleFactor());
    return retval;
}



PyMethodDef PyScale_methods[SCALE_NMETH] = {
    {"Notify", Scale_Notify, METH_VARARGS},
    {"SetScaleFactor", Scale_SetScaleFactor, METH_VARARGS},
    {"GetScaleFactor", Scale_GetScaleFactor, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
Scale_dealloc(PyObject *v)
{
   ScaleObject *obj = (ScaleObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static int
Scale_compare(PyObject *v, PyObject *w)
{
    Scale *a = ((ScaleObject *)v)->data;
    Scale *b = ((ScaleObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

PyObject *
PyScale_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "ScaleFactor") == 0)
        return Scale_GetScaleFactor(self, NULL);

    return Py_FindMethod(PyScale_methods, self, name);
}

int
PyScale_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    PyObject *obj = NULL;

    if(strcmp(name, "ScaleFactor") == 0)
        obj = Scale_SetScaleFactor(self, tuple);

    if(obj != NULL)
        Py_DECREF(obj);

    Py_DECREF(tuple);
    if( obj == NULL)
        PyErr_Format(PyExc_RuntimeError, "Unable to set unknown attribute: '%s'", name);
    return (obj != NULL) ? 0 : -1;
}

static int
Scale_print(PyObject *v, FILE *fp, int flags)
{
    ScaleObject *obj = (ScaleObject *)v;
    fprintf(fp, "%s", PyScale_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
Scale_str(PyObject *v)
{
    ScaleObject *obj = (ScaleObject *)v;
    return PyString_FromString(PyScale_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
#if PY_MAJOR_VERSION > 2 || (PY_MAJOR_VERSION == 2 && PY_MINOR_VERSION >= 5)
static const char *Scale_Purpose = "Set scale factor";
#else
static char *Scale_Purpose = "Set scale factor";
#endif

//
// The type description structure
//
static PyTypeObject ScaleType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "Scale",                    // tp_name
    sizeof(ScaleObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)Scale_dealloc,  // tp_dealloc
    (printfunc)Scale_print,     // tp_print
    (getattrfunc)PyScale_getattr, // tp_getattr
    (setattrfunc)PyScale_setattr, // tp_setattr
    (cmpfunc)Scale_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)Scale_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    Scale_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static Scale *defaultAtts = 0;
static Scale *currentAtts = 0;

static PyObject *
NewScale(int useCurrent)
{
    ScaleObject *newObject;
    newObject = PyObject_NEW(ScaleObject, &ScaleType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new Scale(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new Scale(*defaultAtts);
    else
        newObject->data = new Scale;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapScale(const Scale *attr)
{
    ScaleObject *newObject;
    newObject = PyObject_NEW(ScaleObject, &ScaleType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (Scale *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
Scale_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewScale(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef ScaleMethods[] = {
    {"Scale", Scale_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *ScaleObserver = 0;

std::string
PyScale_GetLogString()
{
    std::string s("Scale = Scale()\n");
    if(currentAtts != 0)
        s += PyScale_ToString(currentAtts, "Scale.");
    return s;
}

static void
PyScale_CallLogRoutine(Subject *subj, void *data)
{
    Scale *atts = (Scale *)subj;
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("Scale = Scale()\n");
        s += PyScale_ToString(currentAtts, "Scale.");
        cb(s);
    }
}

void
PyScale_StartUp(Scale *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyScale_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(ScaleObserver == 0)
    {
        ScaleObserver = new ObserverToCallback(subj,
            PyScale_CallLogRoutine, (void *)data);
    }

}

void
PyScale_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete ScaleObserver;
    ScaleObserver = 0;
}

PyMethodDef *
PyScale_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return ScaleMethods;
}

bool
PyScale_Check(PyObject *obj)
{
    return (obj->ob_type == &ScaleType);
}

Scale *
PyScale_FromPyObject(PyObject *obj)
{
    ScaleObject *obj2 = (ScaleObject *)obj;
    return obj2->data;
}

PyObject *
PyScale_New()
{
    return NewScale(0);
}

PyObject *
PyScale_Wrap(const Scale *attr)
{
    return WrapScale(attr);
}

void
PyScale_SetParent(PyObject *obj, PyObject *parent)
{
    ScaleObject *obj2 = (ScaleObject *)obj;
    obj2->parent = parent;
}

void
PyScale_SetDefaults(const Scale *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new Scale(*atts);
}

