/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <Scale.h>
#include <DataNode.h>

// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Init utility for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void Scale::Init()
{
    ScaleFactor = 0.5;

    Scale::SelectAll();
}

// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Copy utility for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void Scale::Copy(const Scale &obj)
{
    ScaleFactor = obj.ScaleFactor;

    Scale::SelectAll();
}

// Type map format string
const char *Scale::TypeMapFormatString = SCALE_TMFS;
const AttributeGroup::private_tmfs_t Scale::TmfsStruct = {SCALE_TMFS};


// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Default constructor for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale::Scale() : 
    AttributeSubject(Scale::TypeMapFormatString)
{
    Scale::Init();
}

// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Constructor for the derived classes of Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale::Scale(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    Scale::Init();
}

// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Copy constructor for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale::Scale(const Scale &obj) : 
    AttributeSubject(Scale::TypeMapFormatString)
{
    Scale::Copy(obj);
}

// ****************************************************************************
// Method: Scale::Scale
//
// Purpose: 
//   Copy constructor for derived classes of the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale::Scale(const Scale &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    Scale::Copy(obj);
}

// ****************************************************************************
// Method: Scale::~Scale
//
// Purpose: 
//   Destructor for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale::~Scale()
{
    // nothing here
}

// ****************************************************************************
// Method: Scale::operator = 
//
// Purpose: 
//   Assignment operator for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

Scale& 
Scale::operator = (const Scale &obj)
{
    if (this == &obj) return *this;

    Scale::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: Scale::operator == 
//
// Purpose: 
//   Comparison operator == for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
Scale::operator == (const Scale &obj) const
{
    // Create the return value
    return ((ScaleFactor == obj.ScaleFactor));
}

// ****************************************************************************
// Method: Scale::operator != 
//
// Purpose: 
//   Comparison operator != for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
Scale::operator != (const Scale &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: Scale::TypeName
//
// Purpose: 
//   Type name method for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
Scale::TypeName() const
{
    return "Scale";
}

// ****************************************************************************
// Method: Scale::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
Scale::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const Scale *tmp = (const Scale *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: Scale::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
Scale::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new Scale(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: Scale::NewInstance
//
// Purpose: 
//   NewInstance method for the Scale class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
Scale::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new Scale(*this);
    else
        retval = new Scale;

    return retval;
}

// ****************************************************************************
// Method: Scale::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
Scale::SelectAll()
{
    Select(ID_ScaleFactor, (void *)&ScaleFactor);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: Scale::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
Scale::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    Scale defaultObject;
    bool addToParent = false;
    // Create a node for Scale.
    DataNode *node = new DataNode("Scale");

    if(completeSave || !FieldsEqual(ID_ScaleFactor, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("ScaleFactor", ScaleFactor));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: Scale::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
Scale::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("Scale");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("ScaleFactor")) != 0)
        SetScaleFactor(node->AsDouble());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
Scale::SetScaleFactor(double ScaleFactor_)
{
    ScaleFactor = ScaleFactor_;
    Select(ID_ScaleFactor, (void *)&ScaleFactor);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

double
Scale::GetScaleFactor() const
{
    return ScaleFactor;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

